import routes from './routes.js';
import { PAGE_META } from './seo-meta.js';

export const store = Vue.reactive({
    dark: localStorage.getItem('dark') === null ? false : JSON.parse(localStorage.getItem('dark')),
    thumbnails: localStorage.getItem('thumbnails') === null ? true : JSON.parse(localStorage.getItem('thumbnails')),
    levelColoring: localStorage.getItem('levelColoring') === null ? true : JSON.parse(localStorage.getItem('levelColoring')),
    benchmarkMode: false,
    authKey: '',
    sidebarOpen: false,
    showSettings: false,
    showColoringHint: false,
    coloringHintDismissed: localStorage.getItem('coloringHintDismissed') === 'true',
    coloringHintCooldown: (() => {
        const until = Number(localStorage.getItem('coloringHintCooldownUntil') || 0);
        return Date.now() < until;
    })(),
    coloringHintNeverShow: false,
    toggleDark() {
        this.dark = !this.dark;
        localStorage.setItem('dark', JSON.stringify(this.dark));
    },
    saveSetting(key, value) {
        localStorage.setItem(key, JSON.stringify(value));
    },
    dismissColoringHint() {
        this.showColoringHint = false;
        if (this.coloringHintNeverShow) {
            this.coloringHintDismissed = true;
            localStorage.setItem('coloringHintDismissed', 'true');
        }
        // 10 minute cooldown
        this.coloringHintCooldown = true;
        localStorage.setItem('coloringHintCooldownUntil', String(Date.now() + 10 * 60 * 1000));
    },
});

// Migrate old hash URLs to clean URLs so existing bookmarks keep working.
// e.g. ull.pages.dev/#/list  ->  ull.pages.dev/list ,  ull.pages.dev/#/  ->  ull.pages.dev/
// Must run BEFORE the router is created so it initializes on the correct path.
if (window.location.hash.startsWith('#/')) {
    const cleanPath = window.location.hash.slice(1);
    history.replaceState(null, '', cleanPath || '/');
}

// The static, crawlable page content generated by scripts/build-seo.mjs lives
// inside <body id="app">, which is also Vue's in-DOM template. Remove it before
// createApp/mount so Vue never compiles it, and so it does not linger next to
// the real UI once the app is running.
document.getElementById('seo-fallback')?.remove();

const app = Vue.createApp({
    data: () => ({ store }),
});
// Cloudflare Pages serves a directory URL with a trailing slash, so arriving
// straight at ull.pages.dev/listmain lands the router on "/listmain/". Every
// lookup here is keyed without one, and the canonical URL must not grow one
// either, so paths are normalised before anything reads them.
const normalizePath = (p) => (p.length > 1 && p.endsWith('/') ? p.replace(/\/+$/, '') : p);

const router = VueRouter.createRouter({
    history: VueRouter.createWebHistory(),
    routes,
});

// The mobile UI mirrors the desktop pages one-for-one. The map is used twice:
// to send a visitor to the *same* page when switching between the two trees,
// and to canonicalize mobile URLs onto their desktop equivalent so Google does
// not see two copies of every page.
const DESKTOP_TO_MOBILE = {
    '/': '/mobile/home',
    '/home': '/mobile/home',
    '/list': '/mobile/all',
    '/listmain': '/mobile/main',
    '/listfuture': '/mobile/future',
    '/leaderboard': '/mobile/leaderboard',
    '/upcoming': '/mobile/upcoming',
    '/pending': '/mobile/pending',
    '/information': '/mobile/info',
    '/events': '/mobile/events',
};
const MOBILE_TO_DESKTOP = Object.fromEntries(
    Object.entries(DESKTOP_TO_MOBILE).filter(([d]) => d !== '/').map(([d, m]) => [m, d])
);

// Search-engine and AI crawlers mostly identify as mobile devices (Googlebot's
// primary crawler is a smartphone UA). Sending them to /mobile/* would make them
// index the mobile tree under desktop URLs, so they are exempt from the redirect
// and always get the canonical desktop route.
const BOT_UA = /bot|crawler|spider|crawling|slurp|bingpreview|facebookexternalhit|embedly|quora link preview|showyoubot|outbrain|pinterest|vkshare|w3c_validator|whatsapp|telegram|discordbot|lighthouse|chrome-lighthouse|gptbot|oai-searchbot|chatgpt-user|claudebot|claude-web|anthropic-ai|perplexitybot|applebot|amazonbot|bytespider|ccbot|google-extended|duckduckbot|yandex|baiduspider/i;
const isCrawler = () => BOT_UA.test(navigator.userAgent);

// Auto-redirect mobile devices
const isMobile = () => !isCrawler() && (window.innerWidth <= 768 || /Mobi|Android|iPhone|iPad/i.test(navigator.userAgent));
router.beforeEach((to, from, next) => {
    const path = normalizePath(to.path);
    const standalone = path.startsWith('/level/') || path === '/generator' || path === '/admin';
    if (isMobile() && !path.startsWith('/mobile') && !standalone) {
        // Deep links matter: someone arriving on /list from a search result must
        // land on the mobile list, not be dumped on the mobile home page.
        next(DESKTOP_TO_MOBILE[path] || '/mobile');
    } else if (!isMobile() && path.startsWith('/mobile')) {
        next(MOBILE_TO_DESKTOP[path] || '/');
    } else {
        next();
    }
});
// Mark desktop for CSS min-width (user-agent only, not viewport width)
if (!/Mobi|Android|iPhone|iPad/i.test(navigator.userAgent)) {
    document.documentElement.classList.add('desktop');
}

app.use(router);
app.mount('#app');

// Close sidebar overlay when resizing past the collapse breakpoint
window.addEventListener('resize', () => {
    if (window.innerWidth > 1100 && store.sidebarOpen) {
        store.sidebarOpen = false;
    }
});

// Coloring hint popup timer — counts only on list/upcoming pages
const hintPages = ['/list', '/listmain', '/listfuture', '/upcoming'];
let hintElapsed = 0;
let hintInterval = null;

function startHintTimer() {
    if (store.coloringHintDismissed || store.coloringHintCooldown || store.showColoringHint || hintInterval) return;
    hintInterval = setInterval(() => {
        hintElapsed++;
        if (hintElapsed >= 20) {
            store.showColoringHint = true;
            clearInterval(hintInterval);
            hintInterval = null;
        }
    }, 1000);
}

function stopHintTimer() {
    if (hintInterval) {
        clearInterval(hintInterval);
        hintInterval = null;
    }
}

router.afterEach((to) => {
    if (hintPages.includes(to.path)) {
        startHintTimer();
    } else {
        stopHintTimer();
        if (store.showColoringHint) {
            store.dismissColoringHint();
        }
    }
    if (to.path.startsWith('/mobile')) {
        requestAnimationFrame(() => {
            const el = document.querySelector('.mob-content');
            if (el) el.scrollTop = 0;
        });
    }
});

// ── SEO: keep the head in sync with the current route ──────────────────────
// The first paint of every public URL is a real static file generated by
// scripts/build-seo.mjs, so the head is already correct on arrival. This keeps
// it correct across client-side navigations, which never reload the document.
const SITE_ORIGIN = 'https://ull.pages.dev';
const NOT_FOUND_META = {
    title: 'ULL — Page Not Found',
    description: 'This page does not exist on the Upcoming Levels List.',
    noindex: true,
};

function setMeta(selector, attr, value) {
    let el = document.head.querySelector(selector);
    if (!el) {
        el = document.createElement(selector.startsWith('link') ? 'link' : 'meta');
        const [, key, name] = selector.match(/\[(\w+)="([^"]+)"\]/) || [];
        if (key) el.setAttribute(key, name);
        document.head.appendChild(el);
    }
    el.setAttribute(attr, value);
}

router.afterEach((to) => {
    const currentPath = normalizePath(to.path);

    // Level pages are indexable and set their own title once the level loads;
    // without this they would fall through to NOT_FOUND_META and go noindex.
    if (currentPath.startsWith('/level/')) {
        setMeta('link[rel="canonical"]', 'href', SITE_ORIGIN + currentPath);
        setMeta('meta[property="og:url"]', 'content', SITE_ORIGIN + currentPath);
        setMeta('meta[name="robots"]', 'content', 'index, follow');
        return;
    }

    const desktopPath = MOBILE_TO_DESKTOP[currentPath] || currentPath;
    // /home renders the same page as the root "/", which is the canonical URL.
    const canonicalPath = desktopPath === '/home' ? '/' : desktopPath;
    const meta = PAGE_META[canonicalPath] || NOT_FOUND_META;
    const url = SITE_ORIGIN + canonicalPath;

    document.title = meta.title;
    setMeta('meta[name="description"]', 'content', meta.description);
    setMeta('link[rel="canonical"]', 'href', url);
    setMeta('meta[property="og:title"]', 'content', meta.socialTitle || meta.title);
    setMeta('meta[property="og:description"]', 'content', meta.description);
    setMeta('meta[property="og:url"]', 'content', url);
    setMeta('meta[name="twitter:title"]', 'content', meta.socialTitle || meta.title);
    setMeta('meta[name="twitter:description"]', 'content', meta.description);
    // Utility routes (admin, level generator, unknown URLs) must never be indexed.
    setMeta('meta[name="robots"]', 'content', meta.noindex ? 'noindex, follow' : 'index, follow');
});

// Shift+P+O+U to force-show coloring hint popup
const hintKeys = new Set();
window.addEventListener('keydown', (e) => {
    if (e.shiftKey) hintKeys.add(e.key.toLowerCase());
    if (e.shiftKey && hintKeys.has('p') && hintKeys.has('o') && hintKeys.has('u')) {
        store.showColoringHint = true;
        hintKeys.clear();
    }
});
window.addEventListener('keyup', (e) => {
    hintKeys.delete(e.key.toLowerCase());
    if (!e.shiftKey) hintKeys.clear();
});
