// GENERATED by scripts/build-seo.mjs — do not edit by hand.
// Titles and descriptions for client-side navigations; the first paint of each
// URL already carries them from the matching static file.
export const PAGE_META = {
    "/": {
        "title": "Upcoming Levels List",
        "socialTitle": "Upcoming Levels List — Upcoming Geometry Dash Extreme Demons",
        "description": "The Upcoming Levels List ranks every list-worthy upcoming Extreme Demon in Geometry Dash, alongside verified levels, to project what the Demonlist will look like in the future."
    },
    "/list": {
        "title": "ULL — All Levels",
        "socialTitle": "All Levels — Every Upcoming Extreme Demon | Upcoming Levels List",
        "description": "All Levels contains the entire ULL: upcoming Geometry Dash Extreme Demons that are of sufficient quality and have a possibility of being verified in the future."
    },
    "/listmain": {
        "title": "ULL — Main List",
        "socialTitle": "Main List — Rate-Worthy Upcoming Extreme Demons | Upcoming Levels List",
        "description": "The Main List contains all upcoming Geometry Dash Extreme Demons considered to be rate-worthy, which as a result have a higher chance of being added to the Demonlist if they are verified."
    },
    "/listfuture": {
        "title": "ULL — Future List",
        "socialTitle": "Future List — Extreme Demons Closest to Release | Upcoming Levels List",
        "description": "The Future List contains upcoming Geometry Dash Extreme Demons that are expected to be verified in approximately a year or less, ranked by projected Demonlist position."
    },
    "/upcoming": {
        "title": "ULL — Upcoming Levels",
        "socialTitle": "Upcoming Levels — Closest to Verification | Upcoming Levels List",
        "description": "Upcoming Levels ranks Geometry Dash Extreme Demons in the verification stage by how much progress their best run has made, from greatest to least."
    },
    "/pending": {
        "title": "ULL — Pending List",
        "socialTitle": "Pending List — Levels Awaiting Placement | Upcoming Levels List",
        "description": "Pending levels are due for a change to their position: to be placed on the Upcoming Levels List, moved up or down, or removed. Markers represent expected Demonlist placements."
    },
    "/leaderboard": {
        "title": "ULL — Leaderboard",
        "socialTitle": "Leaderboard — Top Players on Upcoming Extreme Demons | Upcoming Levels List",
        "description": "The Upcoming Levels List leaderboard ranks players based on runs they have on upcoming Geometry Dash Extreme Demons and verifications of levels, both rated and unrated."
    },
    "/events": {
        "title": "ULL — Events",
        "socialTitle": "Events — Level of the Day, Month & Closest to Verification | Upcoming Levels List",
        "description": "Event levels are noteworthy upcoming Geometry Dash Extreme Demons chosen by the ULL staff team: Daily and Monthly levels, and the closest level to verification."
    },
    "/information": {
        "title": "ULL — Information",
        "socialTitle": "Guidelines & Information | Upcoming Levels List",
        "description": "How the Upcoming Levels List works: record acceptance and proof requirements, permitted and prohibited software, level placement procedure, level colouring, staff duties and the full ULL guidelines."
    },
    "/generator": {
        "title": "ULL — Level Generator",
        "description": "Internal tool for building Upcoming Levels List entries.",
        "noindex": true
    },
    "/admin": {
        "title": "ULL — Admin",
        "description": "Staff-only administration panel.",
        "noindex": true
    }
};
