#!/usr/bin/env node
// Concatenates the stylesheets into css/bundle.css, in the exact order
// index.html lists them — CSS overrides depend on that order, so it is read
// from the markup rather than maintained separately here.
//
//   node scripts/build-css.mjs
//
// Sources stay where they are and remain the files to edit. Only the bundle is
// served, turning ~23 render-blocking requests into one.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BUNDLE = 'css/bundle.css';
const START = '<!-- css:start';
const END = '<!-- css:end -->';

const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const a = html.indexOf(START);
const b = html.indexOf(END);
if (a === -1 || b === -1) throw new Error(`missing ${START} / ${END} markers in index.html`);

const region = html.slice(a, b);
const files = [...region.matchAll(/href="\/(css\/[^"]+\.css)"/g)].map((m) => m[1]).filter((f) => f !== BUNDLE);
if (!files.length) throw new Error('no stylesheets found between the css markers');

const parts = files.map((rel) => {
    const file = path.join(ROOT, rel);
    if (!fs.existsSync(file)) throw new Error(`index.html references ${rel}, which does not exist`);
    const css = fs.readFileSync(file, 'utf8').replace(/^﻿/, '');
    // url() paths in these files are all root-absolute, so moving the rules
    // into css/bundle.css does not change what they resolve to. Guard against
    // a relative one being introduced later.
    for (const [, url] of css.matchAll(/url\(\s*['"]?([^'")]+)['"]?\s*\)/g)) {
        if (!/^(\/|https?:|data:|#)/.test(url)) {
            throw new Error(`${rel} uses a relative url(${url}); bundling would break it`);
        }
    }
    return `/* ── ${rel} ── */\n${css.trim()}\n`;
});

const bundle = `/* GENERATED by scripts/build-css.mjs — do not edit.\n   Edit the files under css/ and re-run the script. */\n\n${parts.join('\n')}`;
fs.writeFileSync(path.join(ROOT, BUNDLE), bundle);

const rawSize = files.reduce((n, f) => n + fs.statSync(path.join(ROOT, f)).size, 0);
console.log(`bundled ${files.length} stylesheets into ${BUNDLE} (${(rawSize / 1024).toFixed(1)} KB)`);
